### ISSUE TITLE
sequelize가 인덱스를 중복 생성하는 문제

### ISSUE THREAD

**Issue by iHateAI** [Strong-developers/backend#32]
## 에러 메세지
```
'Too many keys specified; max 64 keys allowed'
```

## 에러 발생 원인
모델 수정 이후
```
sequelize.sync({ alter: true });
```
해당 코드로 데이터베이스에 수정 내용을 반영하면 
시퀄라이즈가 계속해서 인덱스를 중복으로 생성하는 것으로 추정

![11111](https://user-images.githubusercontent.com/81323697/201098302-1a4a0214-02a5-466d-ba37-a725100c605b.PNG)

특정 테이블에서만 발생, 관계가 형성된 테이블의 모델을 수정하면 인덱스가 중복 생성 되는 것으로 추정됨

**Comment by iHateAI** [comment]
## 해결

기본키나 외래키와는 상관없는 에러 같습니다. 유니크 제약조건을 걸어준 컬럼에서만 인덱스가 중복 생성 되는데요.

유니크 제약조건을 걸어줄 때 불리언 값 대신 컬럼명을 명시해주면 해결됩니닷!!!

```
// 기존 코드
path: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
    },
```

```
// 변경 코드
path: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: 'path',  // <-- 이 부분
    },
```

**Comment by FoxMon** [comment]
Good
