### ISSUE TITLE
API endpoint 그리고 userId는 어디서 가져올건지에 대하여

### ISSUE THREAD

**Issue by iHateAI** [Strong-developers/backend#34]
1. API endpoint 명세할 때, 언제 query parameter를 쓰고 언제 path variable을 쓸 지
2. 유저의 아이디가 필요할 경우 토큰에서 가져올 건지 아니면 프론트가 직접 API 호출할 때 명시적으로 넣어 보내줄 것인지

**Comment by FoxMon** [comment]
1. https://medium.com/@fullsour/when-should-you-use-path-variable-and-query-parameter-a346790e8a6d
제가 참고한 글입니다.

2. user id의 경우 url에 직접 명시해도 큰 문제는 없을 것 같습니다.
