### ISSUE TITLE
[백엔드] Sequelize include 관련

### ISSUE THREAD

**Issue by robinyeon** [Strong-developers/backend#40]
<img width="938" alt="erd" src="https://user-images.githubusercontent.com/85475577/209033916-8687150b-b527-48dd-becc-b62a99d77824.png">

상기 ERD 확인해보시면 아시겠지만  
피드게시물(FeedPost)에서 공통 유저 정보(User)를 가져오기 위해선 보호소 정보(Shelter)를 거쳐 진행해야합니다.  

현재 제가 진행한 방식은 main에 머지되어 있는 `feed.service.js` #61줄과 같습니다. 하단에 해당 코드 첨부드리니 참고 부탁드려요.  
```js
async findOnePostWithID(id, postId) {
    if (!id) throw ApiError.setBadRequest("Shelter ID is required.");
    if (!postId) throw ApiError.setBadRequest("Post ID is required.");

    const foundPostWithShelterInfo = await FeedPost.findOne({
      where: { id: postId, shelterId: id },
      include: Shelter,
      raw: true,
    });

    const foundShelterWithUserInfo = await Shelter.findOne({
      where: { id: foundPostWithShelterInfo.shelterId },
      include: User,
      raw: true,
    });

    if (!foundPostWithShelterInfo)
      throw ApiError.setBadRequest("Post does not exist.");

    return { foundPostWithShelterInfo, foundShelterWithUserInfo };
  },
```

우선 FeedPost에서 Shelter 정보를 불러오고, 해당 정보에서 다시금 User의 정보를 불러오고 있습니다.  
**FeedPost에서 include를 통해 한번에 User 정보를 불러올 수 있는 방식이 있을지 궁금합니다.**  

공식 문서 확인하고자 하는데 이전에 혹 더 효율적인 방식 아시는 분 계실까 자문 구합니다.

**Comment by iHateAI** [comment]
질문에 대한 답변이 맞을 진 모르겠는데

feeposts에서 보호소 고유 아이디가 13인 데이터의 User 정보를 조회한다고 가정하면

```
SELECT u.id, u.email, u.nickname, u.role, u.profileUrl
FROM feedPosts AS f
INNER JOIN shelters AS s
ON f.shelterId = s.id
INNER JOIN users AS u
ON s.userId = u.id
WHERE f.shelterId = 13;
```

이런식으로 테이블 3개를 조인하면 결과는 아래처럼 나오고

![11111](https://user-images.githubusercontent.com/81323697/209215701-f0604586-2512-43f2-9ff7-ae68a494b8e2.PNG)

이걸 시퀄라이즈 코드로 바꾼다면

```
  const result = await FeedPost.findOne({
    where: { shelterId: 13 },
    attributes: {
      exclude: ['id', 'likes', 'description', 'createdAt', 'updatedAt', 'shelterId', 'userId'],
    },
    include: [
      {
        model: Shelter,
        attributes: {
          exclude: ['id', 'name', 'region', 'phoneNumber', 'description', 'caution', 'createdAt', 'updatedAt', 'userId']
        },
        include: [
          {
            model: User,
            attributes: ["id", "email", "nickname", "role", "profileUrl"],
            
          },
        ],
      },
    ],
    raw: true,
  });

  res.json(result);
```

이런식으로 조인하는 순서대로(feedPost -> shelter -> user) include 중첩하면 되는 것 같습니다.

결과는

![222](https://user-images.githubusercontent.com/81323697/209216466-f603810d-340c-4766-99ac-1d019e12095b.PNG)

필요한 컬럼은 attributes에 추가하거나 exclude 프로펄티 빼시면 될 것 같습니다.

그리고 중첩 객체 없이 flat하게 출력하고 싶어서 raw: true 넣었는데 json으로 결과 response 될 때 테이블명 붙어서 나오는 거 좀 보기 안좋네요.

도움이 되길..★

**Comment by robinyeon** [comment]
확인했습니다. 상세한 설명 감사합니다. 날 쿼리도 좀 더 공부해야겠다..
결국 include 안의 include로 또 불러오는 수 밖에 없는거군요! 뭔가 다른 방식이 있나 싶었어요🤔 고맙습니다!

**Comment by robinyeon** [comment]
혹시나하여 참고용 [Nested eager loading](https://sequelize.org/docs/v7/advanced-association-concepts/eager-loading/#nested-eager-loading) 문서 링크 남깁니다 :))
